import { DefaultTags } from "./tags"

export default function Head() {
	return (
		<>
			<title>Shoply</title>
			<meta name="description" content="Generated by create next app" />
			<DefaultTags />
		</>
	)
}
