import { DefaultTags } from "../tags"

export default function Head() {
	return (
		<>
			<title>Shoply - Sign Up</title>
			<meta name="description" content="Generated by create next app" />
			<DefaultTags />
		</>
	)
}
